# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    description: "A very simple command to print the pipeline ID"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID 



jobs:
  writer-job:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
      - run:
          name: print-hello-to-text-file
          command: |
            cd /tmp
            mkdir -p workspace
            echo "text to output here" > workspace/output.txt
            pwd
      - persist_to_workspace:
          root: /tmp/workspace
          paths: 
            - output.txt

  reader-job: 
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: trying-to-read-workspace
          command: echo "this job is supposed to find the output.txt file"
      - attach_workspace: 
          at: /tmp/workspace2
      - run: |
          if [[ `cat /tmp/workspace2/output.txt` == "text to output here" ]]; then
          cat /tmp/workspace2/output.txt
          else
          echo "something went wrong!"
          fi
      - print_pipeline_id

  # build:
  #   working_directory: ~/mern-starter
  #   docker:
  #     - image: circleci/node:10.16.3
  #     - image: mongo:4.2.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: update-npm
  #         command: 'sudo npm install -g npm@5'
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #     - run:
  #         name: install-npm-wee
  #         command: npm install
  #     - save_cache:
  #         key: dependency-cache-{{ checksum "package-lock.json" }}
  #         paths:
  #           - ./node_modules
  #     - run:
  #         name: test
  #         command: npm test
  #     - run:
  #         name: code-coverage
  #         command: './node_modules/.bin/nyc report --reporter=text-lcov'
  #     - store_artifacts:
  #         path: test-results.xml
  #         prefix: tests
  #     - store_artifacts:
  #         path: coverage
  #         prefix: coverage
  #     - store_test_results:
  #         path: test-results.xml

workflows:
  main-workflow:
    jobs:
      - writer-job
      - reader-job:
          requires:
            - writer-job